--Select [Lot No_] from [San Valero$Item Ledger Entry]
--Update [San Valero$Item Ledger Entry] set [Lot No_]=''
--Select [Item Tracking Code] from [San Valero$Item] 

Update [San Valero$Item] set [Item Tracking Code]=''

Update [San Valero$Item Ledger Entry] set [Lot No_] = ''
Update [San Valero$Item Journal Line] set [Lot No_] = ''
Update [San Valero$Job Ledger Entry] set [Lot No_] = ''
Update [San Valero$Job Journal Line] set [Lot No_] = ''
Update [San Valero$Inventory Buffer] set [Lot No_] = ''
Update [San Valero$Tracking Specification] set [Lot No_] = ''
Update [San Valero$Reservation Entry] set [Lot No_] = ''
Update [San Valero$Entry Summary] set [Lot No_] = ''
Update [San Valero$Job Planning Line] set [Lot No_] = ''
Update [San Valero$Warehouse Activity Line] set [Lot No_] = ''
Update [San Valero$Registered Whse_ Activity Line] set [Lot No_] = ''
Update [San Valero$Lot No_ Information] set [Lot No_] = ''
Update [San Valero$Item Entry Relation] set [Lot No_] = ''
Update [San Valero$Whse_ Item Entry Relation] set [Lot No_] = ''
Update [San Valero$Item Tracing Buffer] set [Lot No_] = ''
Update [San Valero$Record Buffer] set [Lot No_] = ''
Update [San Valero$Whse_ Item Tracking Line] set [Lot No_] = ''
Update [San Valero$Warehouse Journal Line] set [Lot No_] = ''
Update [San Valero$Warehouse Entry] set [Lot No_] = ''
Update [San Valero$Posted Whse_ Receipt Line] set [Lot No_] = ''
Update [San Valero$Bin Content Buffer] set [Lot No_] = ''
Update [San Valero$Posted Invt_ Put-away Line] set [Lot No_] = ''
Update [San Valero$Posted Invt_ Pick Line] set [Lot No_] = ''
Update [San Valero$Inventory Profile] set [Lot No_] = ''
Update [San Valero$Inbound Sales Document Line] set [Lot No_] = ''
Update [San Valero$Inbound Purchase Document Line] set [Lot No_] = ''
Update [San Valero$BizTalk Reservation Entry] set [Lot No_] = ''
