IF OBJECT_ID('dbo.Country', 'U') IS NOT NULL 
	DROP TABLE [dbo].Country

CREATE TABLE [Country] 
(
    [Code]	VARCHAR(512),
    [Name]	VARCHAR(512),
    [ISO2Code]	VARCHAR(512),
    [ISO3Code]	VARCHAR(512),
    [OITRegion]	VARCHAR(512),
    [OITSubregion]	VARCHAR(512),
    [OITCountryZone]	VARCHAR(512),
    [WorldBankIncomeGroup]	VARCHAR(512),
    [Continent]	VARCHAR(512),
    [EuropeZone]	VARCHAR(512),
    [CountryKey]	INT
);

INSERT INTO [Country] ([Code], [Name], [ISO2Code], [ISO3Code], [OITRegion], [OITSubregion], [OITCountryZone], [WorldBankIncomeGroup], [Continent], [EuropeZone], [CountryKey]) VALUES
	('AF', 'Afganistán', 'AF', 'AFG', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso bajo', 'Asia', 'N/A', '1'),
	('AL', 'Albania', 'AL', 'ALB', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso mediano alto', 'Europa', 'Resto de Europa', '2'),
	('DE', 'Alemania', 'DE', 'DEU', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Unión Europea', '3'),
	('AD', 'Andorra', 'AD', 'AND', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '4'),
	('AO', 'Angola', 'AO', 'AGO', 'África', 'África subsahariana', 'África central', 'Ingreso mediano bajo', 'África', 'N/A', '5'),
	('AI', 'Anguila', 'AI', 'AIA', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '6'),
	('AQ', 'Antártida', 'AQ', 'ATA', 'Antartida', 'Antartida', 'Antartida', 'N/A', 'Antartida', 'N/A', '7'),
	('AG', 'Antigua y Barbuda', 'AG', 'ATG', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '8'),
	('SA', 'Arabia Saudita', 'SA', 'SAU', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso alto', 'Asia', 'N/A', '9'),
	('DZ', 'Argelia', 'DZ', 'DZA', 'África', 'Norte de África', 'Norte de África', 'Ingreso mediano bajo', 'África', 'N/A', '10'),
	('AR', 'Argentina', 'AR', 'ARG', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '11'),
	('AM', 'Armenia', 'AM', 'ARM', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia occidental', 'Ingreso mediano alto', 'Asia', 'N/A', '12'),
	('AW', 'Aruba', 'AW', 'ABW', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '13'),
	('AU', 'Australia', 'AU', 'AUS', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '14'),
	('AT', 'Austria', 'AT', 'AUT', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Unión Europea', '15'),
	('AZ', 'Azerbaiyán', 'AZ', 'AZE', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia occidental', 'Ingreso mediano alto', 'Asia', 'N/A', '16'),
	('BE', 'Bélgica', 'BE', 'BEL', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Unión Europea', '17'),
	('BS', 'Bahamas', 'BS', 'BHS', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '18'),
	('BH', 'Bahrein', 'BH', 'BHR', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso alto', 'Asia', 'N/A', '19'),
	('BD', 'Bangladesh', 'BD', 'BGD', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso mediano bajo', 'Asia', 'N/A', '20'),
	('BB', 'Barbados', 'BB', 'BRB', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '21'),
	('BZ', 'Belice', 'BZ', 'BLZ', 'Américas', 'América Latina y el Caribe', 'América Central', 'Ingreso mediano alto', 'América del Sur', 'N/A', '22'),
	('BJ', 'Benín', 'BJ', 'BEN', 'África', 'África subsahariana', 'África Occidental', 'Ingreso mediano bajo', 'África', 'N/A', '23'),
	('BT', 'Bhután', 'BT', 'BTN', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso mediano bajo', 'Asia', 'N/A', '24'),
	('BY', 'Bielorrusia', 'BY', 'BLR', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso mediano alto', 'Europa', 'Resto de Europa', '25'),
	('MM', 'Birmania', 'MM', 'MMR', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano bajo', 'Asia', 'N/A', '26'),
	('BO', 'Bolivia', 'BO', 'BOL', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano bajo', 'América del Sur', 'N/A', '27'),
	('BA', 'Bosnia y Herzegovina', 'BA', 'BIH', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso mediano alto', 'Europa', 'Resto de Europa', '28'),
	('BW', 'Botsuana', 'BW', 'BWA', 'África', 'África subsahariana', 'África del Sur', 'Ingreso mediano alto', 'África', 'N/A', '29'),
	('BR', 'Brasil', 'BR', 'BRA', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '30'),
	('BN', 'Brunéi', 'BN', 'BRN', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso alto', 'Asia', 'N/A', '31'),
	('BG', 'Bulgaria', 'BG', 'BGR', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso mediano alto', 'Europa', 'Unión Europea', '32'),
	('BF', 'Burkina Faso', 'BF', 'BFA', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '33'),
	('BI', 'Burundi', 'BI', 'BDI', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '34'),
	('CV', 'Cabo Verde', 'CV', 'CPV', 'África', 'África subsahariana', 'África Occidental', 'Ingreso mediano bajo', 'África', 'N/A', '35'),
	('KH', 'Camboya', 'KH', 'KHM', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano bajo', 'Asia', 'N/A', '36'),
	('CM', 'Camerún', 'CM', 'CMR', 'África', 'África subsahariana', 'África central', 'Ingreso mediano bajo', 'África', 'N/A', '37'),
	('CA', 'Canadá', 'CA', 'CAN', 'Américas', 'América del Norte', 'América del Norte', 'Ingreso alto', 'América del Norte', 'N/A', '38'),
	('TD', 'Chad', 'TD', 'TCD', 'África', 'África subsahariana', 'África central', 'Ingreso bajo', 'África', 'N/A', '39'),
	('CL', 'Chile', 'CL', 'CHL', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso alto', 'América del Sur', 'N/A', '40'),
	('CN', 'China', 'CN', 'CHN', 'Asia y el Pacífico', 'Asia Oriental', 'Asia Oriental', 'Ingreso mediano alto', 'Asia', 'N/A', '41'),
	('CY', 'Chipre', 'CY', 'CYP', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia occidental', 'Ingreso alto', 'Asia', 'Unión Europea', '42'),
	('VA', 'Ciudad del Vaticano', 'VA', 'VAT', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '43'),
	('CO', 'Colombia', 'CO', 'COL', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '44'),
	('KM', 'Comoras', 'KM', 'COM', 'África', 'África subsahariana', 'África Oriental', 'Ingreso mediano bajo', 'África', 'N/A', '45'),
	('CG', 'República del Congo', 'CG', 'COG', 'África', 'África subsahariana', 'África central', 'Ingreso mediano bajo', 'África', 'N/A', '46'),
	('CD', 'República Democrática del Congo', 'CD', 'COD', 'África', 'África subsahariana', 'África central', 'Ingreso bajo', 'África', 'N/A', '47'),
	('KP', 'Corea del Norte', 'KP', 'PRK', 'Asia y el Pacífico', 'Asia Oriental', 'Asia Oriental', 'Ingreso bajo', 'Asia', 'N/A', '48'),
	('KR', 'Corea del Sur', 'KR', 'KOR', 'Asia y el Pacífico', 'Asia Oriental', 'Asia Oriental', 'Ingreso alto', 'Asia', 'N/A', '49'),
	('CI', 'Costa de Marfil', 'CI', 'CIV', 'África', 'África subsahariana', 'África Occidental', 'Ingreso mediano bajo', 'África', 'N/A', '50'),
	('CR', 'Costa Rica', 'CR', 'CRI', 'Américas', 'América Latina y el Caribe', 'América Central', 'Ingreso mediano alto', 'América del Sur', 'N/A', '51'),
	('HR', 'Croacia', 'HR', 'HRV', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '52'),
	('CU', 'Cuba', 'CU', 'CUB', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '53'),
	('CW', 'Curazao (NL)', 'CW', 'CWU', 'N/A', 'N/A', 'N/A', 'N/A', 'Europa', 'Unión Europea', '54'),
	('DK', 'Dinamarca', 'DK', 'DNK', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '55'),
	('DM', 'Dominica', 'DM', 'DMA', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '56'),
	('EC', 'Ecuador', 'EC', 'ECU', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '57'),
	('EG', 'Egipto', 'EG', 'EGY', 'África', 'Norte de África', 'Norte de África', 'Ingreso mediano bajo', 'África', 'N/A', '58'),
	('SV', 'El Salvador', 'SV', 'SLV', 'Américas', 'América Latina y el Caribe', 'América Central', 'Ingreso mediano bajo', 'América del Sur', 'N/A', '59'),
	('AE', 'Emiratos Árabes Unidos', 'AE', 'ARE', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso alto', 'Asia', 'N/A', '60'),
	('ER', 'Eritrea', 'ER', 'ERI', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '61'),
	('SK', 'Eslovaquia', 'SK', 'SVK', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso alto', 'Europa', 'Unión Europea', '62'),
	('SI', 'Eslovenia', 'SI', 'SVN', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '63'),
	('ES', 'España', 'ES', 'ESP', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '64'),
	('US', 'Estados Unidos de América', 'US', 'USA', 'Américas', 'América del Norte', 'América del Norte', 'Ingreso alto', 'América del Norte', 'N/A', '65'),
	('EE', 'Estonia', 'EE', 'EST', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '66'),
	('ET', 'Etiopía', 'ET', 'ETH', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '67'),
	('PH', 'Filipinas', 'PH', 'PHL', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano bajo', 'Asia', 'N/A', '68'),
	('FI', 'Finlandia', 'FI', 'FIN', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '69'),
	('FJ', 'Fiyi', 'FJ', 'FJI', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano alto', 'Oceanía', 'N/A', '70'),
	('FR', 'Francia', 'FR', 'FRA', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Unión Europea', '71'),
	('GA', 'Gabón', 'GA', 'GAB', 'África', 'África subsahariana', 'África central', 'Ingreso mediano alto', 'África', 'N/A', '72'),
	('GM', 'Gambia', 'GM', 'GMB', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '73'),
	('GE', 'Georgia', 'GE', 'GEO', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia occidental', 'Ingreso mediano alto', 'Asia', 'N/A', '74'),
	('GH', 'Ghana', 'GH', 'GHA', 'África', 'África subsahariana', 'África Occidental', 'Ingreso mediano bajo', 'África', 'N/A', '75'),
	('GI', 'Gibraltar', 'GI', 'GIB', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '76'),
	('GD', 'Granada', 'GD', 'GRD', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '77'),
	('GR', 'Grecia', 'GR', 'GRC', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '78'),
	('GL', 'Groenlandia', 'GL', 'GRL', 'Américas', 'América del Norte', 'América del Norte', 'Ingreso alto', 'América del Norte', 'N/A', '79'),
	('GP', 'Guadalupe', 'GP', 'GLP', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '80'),
	('GU', 'Guam', 'GU', 'GUM', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '81'),
	('GT', 'Guatemala', 'GT', 'GTM', 'Américas', 'América Latina y el Caribe', 'América Central', 'Ingreso mediano alto', 'América del Sur', 'N/A', '82'),
	('GF', 'Guayana Francesa', 'GF', 'GUF', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso alto', 'América del Sur', 'N/A', '83'),
	('GG', 'Guernsey', 'GG', 'GGY', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Resto de Europa', '84'),
	('GN', 'Guinea', 'GN', 'GIN', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '85'),
	('GQ', 'Guinea Ecuatorial', 'GQ', 'GNQ', 'África', 'África subsahariana', 'África central', 'Ingreso mediano alto', 'África', 'N/A', '86'),
	('GW', 'Guinea-Bissau', 'GW', 'GNB', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '87'),
	('GY', 'Guyana', 'GY', 'GUY', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '88'),
	('HT', 'Haití', 'HT', 'HTI', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano bajo', 'América del Sur', 'N/A', '89'),
	('HN', 'Honduras', 'HN', 'HND', 'Américas', 'América Latina y el Caribe', 'América Central', 'Ingreso mediano bajo', 'América del Sur', 'N/A', '90'),
	('HK', 'Hong kong', 'HK', 'HKG', 'Asia y el Pacífico', 'Asia Oriental', 'Asia Oriental', 'Ingreso alto', 'Asia', 'N/A', '91'),
	('HU', 'Hungría', 'HU', 'HUN', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso alto', 'Europa', 'Unión Europea', '92'),
	('IN', 'India', 'IN', 'IND', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso mediano bajo', 'Asia', 'N/A', '93'),
	('ID', 'Indonesia', 'ID', 'IDN', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano bajo', 'Asia', 'N/A', '94'),
	('IR', 'Irán', 'IR', 'IRN', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso mediano bajo', 'Asia', 'N/A', '95'),
	('IQ', 'Irak', 'IQ', 'IRQ', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso mediano alto', 'Asia', 'N/A', '96'),
	('IE', 'Irlanda', 'IE', 'IRL', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '97'),
	('BV', 'Isla Bouvet', 'BV', 'BVT', 'N/A', 'N/A', 'N/A', 'N/A', 'Antartida', 'N/A', '98'),
	('IM', 'Isla de Man', 'IM', 'IMN', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '99'),
	('CX', 'Isla de Navidad (AUS)', 'CX', 'CXR', 'N/A', 'N/A', 'N/A', 'N/A', 'Oceanía', 'N/A', '100'),
	('NF', 'Isla Norfolk', 'NF', 'NFK', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '101'),
	('IS', 'Islandia', 'IS', 'ISL', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '102'),
	('BM', 'Islas Bermudas', 'BM', 'BMU', 'Américas', 'América del Norte', 'América del Norte', 'Ingreso alto', 'América del Norte', 'N/A', '103'),
	('KY', 'Islas Caimán', 'KY', 'CYM', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '104'),
	('CC', 'Islas Cocos (AUS)', 'CC', 'CCK', 'N/A', 'N/A', 'N/A', 'N/A', 'Oceanía', 'N/A', '105'),
	('CK', 'Islas Cook', 'CK', 'COK', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano alto', 'Oceanía', 'N/A', '106'),
	('AX', 'Islas de Åland (FI)', 'AX', 'ALA', 'N/A', 'N/A', 'N/A', 'N/A', 'Europa', 'Unión Europea', '107'),
	('FO', 'Islas Feroe', 'FO', 'FRO', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '108'),
	('GS', 'Islas Georgias del Sur y Sandwich del Sur', 'GS', 'SGS', 'N/A', 'N/A', 'N/A', 'N/A', 'Antartida', 'N/A', '109'),
	('HM', 'Islas Heard y McDonald (AUS)', 'HM', 'HMD', 'N/A', 'N/A', 'N/A', 'N/A', 'Oceanía', 'N/A', '110'),
	('MV', 'Islas Maldivas', 'MV', 'MDV', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso mediano alto', 'Asia', 'N/A', '111'),
	('FK', 'Islas Malvinas', 'FK', 'FLK', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso alto', 'América del Sur', 'N/A', '112'),
	('MP', 'Islas Marianas del Norte', 'MP', 'MNP', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '113'),
	('MH', 'Islas Marshall', 'MH', 'MHL', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano alto', 'Oceanía', 'N/A', '114'),
	('PN', 'Islas Pitcairn (UK)', 'PN', 'PCN', 'N/A', 'N/A', 'N/A', 'N/A', 'Europa', 'Resto de Europa', '115'),
	('SB', 'Islas Salomón', 'SB', 'SLB', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano bajo', 'Oceanía', 'N/A', '116'),
	('TC', 'Islas Turcas y Caicos', 'TC', 'TCA', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '117'),
	('UM', 'Islas Ultramarinas Menores de Estados Unidos', 'UM', 'UMI', 'N/A', 'N/A', 'N/A', 'N/A', 'América', 'N/A', '118'),
	('VG', 'Islas Vírgenes Británicas', 'VG', 'VGB', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '119'),
	('VI', 'Islas Vírgenes de los Estados Unidos', 'VI', 'VIR', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '120'),
	('IL', 'Israel', 'IL', 'ISR', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia occidental', 'Ingreso alto', 'Asia', 'N/A', '121'),
	('IT', 'Italia', 'IT', 'ITA', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '122'),
	('JM', 'Jamaica', 'JM', 'JAM', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '123'),
	('JP', 'Japón', 'JP', 'JPN', 'Asia y el Pacífico', 'Asia Oriental', 'Asia Oriental', 'Ingreso alto', 'Asia', 'N/A', '124'),
	('JE', 'Jersey', 'JE', 'JEY', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Resto de Europa', '125'),
	('JO', 'Jordania', 'JO', 'JOR', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso mediano alto', 'Asia', 'N/A', '126'),
	('KZ', 'Kazajistán', 'KZ', 'KAZ', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia Central', 'Ingreso mediano alto', 'Asia', 'N/A', '127'),
	('KE', 'Kenia', 'KE', 'KEN', 'África', 'África subsahariana', 'África Oriental', 'Ingreso mediano bajo', 'África', 'N/A', '128'),
	('KG', 'Kirguistán', 'KG', 'KGZ', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia Central', 'Ingreso mediano bajo', 'Asia', 'N/A', '129'),
	('KI', 'Kiribati', 'KI', 'KIR', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano bajo', 'Oceanía', 'N/A', '130'),
	('KW', 'Kuwait', 'KW', 'KWT', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso alto', 'Asia', 'N/A', '131'),
	('LB', 'Líbano', 'LB', 'LBN', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso mediano bajo', 'Asia', 'N/A', '132'),
	('LA', 'Laos', 'LA', 'LAO', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano bajo', 'Asia', 'N/A', '133'),
	('LS', 'Lesoto', 'LS', 'LSO', 'África', 'África subsahariana', 'África del Sur', 'Ingreso mediano bajo', 'África', 'N/A', '134'),
	('LV', 'Letonia', 'LV', 'LVA', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '135'),
	('LR', 'Liberia', 'LR', 'LBR', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '136'),
	('LY', 'Libia', 'LY', 'LBY', 'África', 'Norte de África', 'Norte de África', 'Ingreso mediano alto', 'África', 'N/A', '137'),
	('LI', 'Liechtenstein', 'LI', 'LIE', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Resto de Europa', '138'),
	('LT', 'Lituania', 'LT', 'LTU', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '139'),
	('LU', 'Luxemburgo', 'LU', 'LUX', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Unión Europea', '140'),
	('MX', 'México', 'MX', 'MEX', 'Américas', 'América Latina y el Caribe', 'América Central', 'Ingreso mediano alto', 'América del Sur', 'N/A', '141'),
	('MC', 'Mónaco', 'MC', 'MCO', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Resto de Europa', '142'),
	('MO', 'Macao', 'MO', 'MAC', 'Asia y el Pacífico', 'Asia Oriental', 'Asia Oriental', 'Ingreso alto', 'Asia', 'N/A', '143'),
	('MK', 'Macedônia', 'MK', 'MKD', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso mediano alto', 'Europa', 'Resto de Europa', '144'),
	('MG', 'Madagascar', 'MG', 'MDG', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '145'),
	('MY', 'Malasia', 'MY', 'MYS', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano alto', 'Asia', 'N/A', '146'),
	('MW', 'Malawi', 'MW', 'MWI', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '147'),
	('ML', 'Mali', 'ML', 'MLI', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '148'),
	('MT', 'Malta', 'MT', 'MLT', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '149'),
	('MA', 'Marruecos', 'MA', 'MAR', 'África', 'Norte de África', 'Norte de África', 'Ingreso mediano bajo', 'África', 'N/A', '150'),
	('MQ', 'Martinica', 'MQ', 'MTQ', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '151'),
	('MU', 'Mauricio', 'MU', 'MUS', 'África', 'África subsahariana', 'África Oriental', 'Ingreso mediano alto', 'África', 'N/A', '152'),
	('MR', 'Mauritania', 'MR', 'MRT', 'África', 'África subsahariana', 'África Occidental', 'Ingreso mediano bajo', 'África', 'N/A', '153'),
	('YT', 'Mayotte', 'YT', 'MYT', 'África', 'África subsahariana', 'África Oriental', 'Ingreso mediano bajo', 'África', 'N/A', '154'),
	('FM', 'Micronesia', 'FM', 'FSM', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano bajo', 'Oceanía', 'N/A', '155'),
	('MD', 'Moldavia', 'MD', 'MDA', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso mediano alto', 'Europa', 'Resto de Europa', '156'),
	('MN', 'Mongolia', 'MN', 'MNG', 'Asia y el Pacífico', 'Asia Oriental', 'Asia Oriental', 'Ingreso mediano bajo', 'Asia', 'N/A', '157'),
	('ME', 'Montenegro', 'ME', 'MNE', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso mediano alto', 'Europa', 'Resto de Europa', '158'),
	('MS', 'Montserrat', 'MS', 'MSR', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '159'),
	('MZ', 'Mozambique', 'MZ', 'MOZ', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '160'),
	('NA', 'Namibia', 'NA', 'NAM', 'África', 'África subsahariana', 'África del Sur', 'Ingreso mediano alto', 'África', 'N/A', '161'),
	('NR', 'Nauru', 'NR', 'NRU', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '162'),
	('NP', 'Nepal', 'NP', 'NPL', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso mediano bajo', 'Asia', 'N/A', '163'),
	('NI', 'Nicaragua', 'NI', 'NIC', 'Américas', 'América Latina y el Caribe', 'América Central', 'Ingreso mediano bajo', 'América del Sur', 'N/A', '164'),
	('NE', 'Niger', 'NE', 'NER', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '165'),
	('NG', 'Nigeria', 'NG', 'NGA', 'África', 'África subsahariana', 'África Occidental', 'Ingreso mediano bajo', 'África', 'N/A', '166'),
	('NU', 'Niue', 'NU', 'NIU', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '167'),
	('NO', 'Noruega', 'NO', 'NOR', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '168'),
	('NC', 'Nueva Caledonia', 'NC', 'NCL', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '169'),
	('NZ', 'Nueva Zelanda', 'NZ', 'NZL', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '170'),
	('OM', 'Omán', 'OM', 'OMN', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso alto', 'Asia', 'N/A', '171'),
	('NL', 'Países Bajos', 'NL', 'NLD', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Unión Europea', '172'),
	('PK', 'Pakistán', 'PK', 'PAK', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso mediano bajo', 'Asia', 'N/A', '173'),
	('PW', 'Palau', 'PW', 'PLW', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano alto', 'Oceanía', 'N/A', '174'),
	('PS', 'Palestina', 'PS', 'PSE', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso mediano bajo', 'Asia', 'N/A', '175'),
	('PA', 'Panamá', 'PA', 'PAN', 'Américas', 'América Latina y el Caribe', 'América Central', 'Ingreso alto', 'América del Sur', 'N/A', '176'),
	('PG', 'Papúa Nueva Guinea', 'PG', 'PNG', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano bajo', 'Oceanía', 'N/A', '177'),
	('PY', 'Paraguay', 'PY', 'PRY', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '178'),
	('PE', 'Perú', 'PE', 'PER', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '179'),
	('PF', 'Polinesia Francesa', 'PF', 'PYF', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '180'),
	('PL', 'Polonia', 'PL', 'POL', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso alto', 'Europa', 'Unión Europea', '181'),
	('PT', 'Portugal', 'PT', 'PRT', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '182'),
	('PR', 'Puerto Rico', 'PR', 'PRI', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '183'),
	('QA', 'Qatar', 'QA', 'QAT', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso alto', 'Asia', 'N/A', '184'),
	('GB', 'Reino Unido', 'GB', 'GBR', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '185'),
	('CF', 'República Centroafricana', 'CF', 'CAF', 'África', 'África subsahariana', 'África central', 'Ingreso bajo', 'África', 'N/A', '186'),
	('CZ', 'República Checa', 'CZ', 'CZE', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso alto', 'Europa', 'Unión Europea', '187'),
	('DO', 'República Dominicana', 'DO', 'DOM', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '188'),
	('SS', 'República de Sudán del Sur', 'SS', 'SSD', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '189'),
	('RE', 'Reunión', 'RE', 'REU', 'África', 'África subsahariana', 'África Oriental', 'Ingreso alto', 'África', 'N/A', '190'),
	('RW', 'Ruanda', 'RW', 'RWA', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '191'),
	('RO', 'Rumanía', 'RO', 'ROU', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso alto', 'Europa', 'Unión Europea', '192'),
	('RU', 'Rusia', 'RU', 'RUS', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso mediano alto', 'Europa', 'Resto de Europa', '193'),
	('EH', 'Sahara Occidental', 'EH', 'ESH', 'África', 'Norte de África', 'Norte de África', 'Ingreso mediano bajo', 'África', 'N/A', '194'),
	('WS', 'Samoa', 'WS', 'WSM', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano bajo', 'Oceanía', 'N/A', '195'),
	('AS', 'Samoa Americana', 'AS', 'ASM', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano alto', 'Oceanía', 'N/A', '196'),
	('BL', 'San Bartolomé (FR)', 'BL', 'BLM', 'N/A', 'N/A', 'N/A', 'N/A', 'Europa', 'Resto de Europa', '197'),
	('KN', 'San Cristóbal y Nieves', 'KN', 'KNA', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '198'),
	('SM', 'San Marino', 'SM', 'SMR', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso alto', 'Europa', 'Resto de Europa', '199'),
	('MF', 'San Martín (Francia)', 'MF', 'MAF', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '200'),
	('PM', 'San Pedro y Miquelón', 'PM', 'SPM', 'Américas', 'América del Norte', 'América del Norte', 'Ingreso alto', 'América del Norte', 'N/A', '201'),
	('VC', 'San Vicente y las Granadinas', 'VC', 'VCT', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '202'),
	('SH', 'Santa Elena', 'SH', 'SHN', 'África', 'África subsahariana', 'África Occidental', 'Ingreso mediano bajo', 'África', 'N/A', '203'),
	('LC', 'Santa Lucía', 'LC', 'LCA', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso mediano alto', 'América del Sur', 'N/A', '204'),
	('ST', 'Santo Tomé y Príncipe', 'ST', 'STP', 'África', 'África subsahariana', 'África central', 'Ingreso mediano bajo', 'África', 'N/A', '205'),
	('SN', 'Senegal', 'SN', 'SEN', 'África', 'África subsahariana', 'África Occidental', 'Ingreso mediano bajo', 'África', 'N/A', '206'),
	('RS', 'Serbia', 'RS', 'SRB', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Sur de Europa', 'Ingreso mediano alto', 'Europa', 'Resto de Europa', '207'),
	('SC', 'Seychelles', 'SC', 'SYC', 'África', 'África subsahariana', 'África Oriental', 'Ingreso alto', 'África', 'N/A', '208'),
	('SL', 'Sierra Leona', 'SL', 'SLE', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '209'),
	('SG', 'Singapur', 'SG', 'SGP', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso alto', 'Asia', 'N/A', '210'),
	('SX', 'Sint Maarten (NL)', 'SX', 'SMX', 'N/A', 'N/A', 'N/A', 'N/A', 'Europa', 'Unión Europea', '211'),
	('SY', 'Siria', 'SY', 'SYR', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso bajo', 'Asia', 'N/A', '212'),
	('SO', 'Somalia', 'SO', 'SOM', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '213'),
	('LK', 'Sri lanka', 'LK', 'LKA', 'Asia y el Pacífico', 'Asia meridonal', 'Asia meridonal', 'Ingreso mediano bajo', 'Asia', 'N/A', '214'),
	('ZA', 'Sudáfrica', 'ZA', 'ZAF', 'África', 'África subsahariana', 'África del Sur', 'Ingreso mediano alto', 'África', 'N/A', '215'),
	('SD', 'Sudán', 'SD', 'SDN', 'África', 'Norte de África', 'Norte de África', 'Ingreso bajo', 'África', 'N/A', '216'),
	('SE', 'Suecia', 'SE', 'SWE', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Norte de Europa', 'Ingreso alto', 'Europa', 'Unión Europea', '217'),
	('CH', 'Suiza', 'CH', 'CHE', 'Europa y Asia Central', 'Europa del Norte, Sur y Occidental', 'Europa occidental', 'Ingreso alto', 'Europa', 'Resto de Europa', '218'),
	('SR', 'Surinám', 'SR', 'SUR', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '219'),
	('SJ', 'Svalbard y Jan Mayen (NO)', 'SJ', 'SJM', 'N/A', 'N/A', 'N/A', 'N/A', 'Europa', 'Unión Europea', '220'),
	('SZ', 'Swazilandia', 'SZ', 'SWZ', 'África', 'África subsahariana', 'África del Sur', 'Ingreso mediano bajo', 'África', 'N/A', '221'),
	('TJ', 'Tayikistán', 'TJ', 'TJK', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia Central', 'Ingreso mediano bajo', 'Asia', 'N/A', '222'),
	('TH', 'Tailandia', 'TH', 'THA', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano alto', 'Asia', 'N/A', '223'),
	('TW', 'Taiwán', 'TW', 'TWN', 'Asia y el Pacífico', 'Asia Oriental', 'Asia Oriental', 'Ingreso alto', 'Asia', 'N/A', '224'),
	('TZ', 'Tanzania', 'TZ', 'TZA', 'África', 'África subsahariana', 'África Oriental', 'Ingreso mediano bajo', 'África', 'N/A', '225'),
	('IO', 'Territorio Británico del Océano Índico (UK)', 'IO', 'IOT', 'N/A', 'N/A', 'N/A', 'N/A', 'Europa', 'Resto de Europa', '226'),
	('TF', 'Territorios Australes y Antárticas Franceses (FR)', 'TF', 'ATF', 'N/A', 'N/A', 'N/A', 'N/A', 'Europa', 'Unión Europea', '227'),
	('TL', 'Timor Oriental', 'TL', 'TLS', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano bajo', 'Asia', 'N/A', '228'),
	('TG', 'Togo', 'TG', 'TGO', 'África', 'África subsahariana', 'África Occidental', 'Ingreso bajo', 'África', 'N/A', '229'),
	('TK', 'Tokelau', 'TK', 'TKL', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano bajo', 'Oceanía', 'N/A', '230'),
	('TO', 'Tonga', 'TO', 'TON', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano alto', 'Oceanía', 'N/A', '231'),
	('TT', 'Trinidad y Tobago', 'TT', 'TTO', 'Américas', 'América Latina y el Caribe', 'Caribe', 'Ingreso alto', 'América del Sur', 'N/A', '232'),
	('TN', 'Tunez', 'TN', 'TUN', 'África', 'Norte de África', 'Norte de África', 'Ingreso mediano bajo', 'África', 'N/A', '233'),
	('TM', 'Turkmenistán', 'TM', 'TKM', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia Central', 'Ingreso mediano alto', 'Asia', 'N/A', '234'),
	('TR', 'Turquía', 'TR', 'TUR', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia occidental', 'Ingreso mediano alto', 'Asia', 'N/A', '235'),
	('TV', 'Tuvalu', 'TV', 'TUV', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano alto', 'Oceanía', 'N/A', '236'),
	('UA', 'Ucrania', 'UA', 'UKR', 'Europa y Asia Central', 'Europa oriental', 'Europa oriental', 'Ingreso mediano bajo', 'Europa', 'Resto de Europa', '237'),
	('UG', 'Uganda', 'UG', 'UGA', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '238'),
	('UY', 'Uruguay', 'UY', 'URY', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso alto', 'América del Sur', 'N/A', '239'),
	('UZ', 'Uzbekistán', 'UZ', 'UZB', 'Europa y Asia Central', 'Asia Central y Occidental', 'Asia Central', 'Ingreso mediano bajo', 'Asia', 'N/A', '240'),
	('VU', 'Vanuatu', 'VU', 'VUT', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso mediano bajo', 'Oceanía', 'N/A', '241'),
	('VE', 'Venezuela', 'VE', 'VEN', 'Américas', 'América Latina y el Caribe', 'América del Sur', 'Ingreso mediano alto', 'América del Sur', 'N/A', '242'),
	('VN', 'Vietnam', 'VN', 'VNM', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Asia Sudoriental', 'Ingreso mediano bajo', 'Asia', 'N/A', '243'),
	('WF', 'Wallis y Futuna', 'WF', 'WLF', 'Asia y el Pacífico', 'Asia sudoriental y el Pacífico', 'Islas del Pacífico', 'Ingreso alto', 'Oceanía', 'N/A', '244'),
	('YE', 'Yemen', 'YE', 'YEM', 'Estados Árabes', 'Estados Árabes', 'Estados Árabes', 'Ingreso bajo', 'Asia', 'N/A', '245'),
	('DJ', 'Yibuti', 'DJ', 'DJI', 'África', 'África subsahariana', 'África Oriental', 'Ingreso mediano bajo', 'África', 'N/A', '246'),
	('ZM', 'Zambia', 'ZM', 'ZMB', 'África', 'África subsahariana', 'África Oriental', 'Ingreso bajo', 'África', 'N/A', '247'),
	('ZW', 'Zimbabue', 'ZW', 'ZWE', 'África', 'África subsahariana', 'África Oriental', 'Ingreso mediano bajo', 'África', 'N/A', '248');